Repository christfellowshipchurch/web-app, pull requests merged in 2020-09, with the labels that each got.

#161 Fix Group time not showing up on group card
  src/groups/GroupListConnected/GroupList.js
  src/groups/GroupListConnected/dateLabel.js
Labels: merge, ready for review

#162 Use nicknames in groups
  src/groups/GroupContentItemConnected/GroupContentItem.js
  src/groups/GroupContentItemConnected/getGroup.js
  src/groups/GroupContentItemConnected/index.js
Labels: ready for review

#164 Use consistent date formatting on individual group pages
  src/groups/GroupContentItemConnected/GroupContentItem.js
  src/groups/GroupContentItemConnected/getGroup.js
  src/groups/GroupContentItemConnected/index.js
  src/groups/GroupListConnected/GroupList.js
  src/groups/dateTextFormat.js
Labels: merge, ready for review

#165 [Events] Chat Direct Messages
  package.json
  src/content-single/EventContentItem/components/DirectMessagesChat.js
  src/content-single/EventContentItem/components/DirectMessagesDropdown.js
  src/content-single/EventContentItem/components/EventChat.js
  src/content-single/EventContentItem/components/EventPanel.js
  src/content-single/EventContentItem/components/LiveStreamChat.js
  src/content-single/EventContentItem/index.sandbox.js
  src/styles/css/stream-chat-react.overrides.css
  src/styles/theme.js
  src/ui/chat/Message.js
  src/ui/chat/MessageInput.js
  yarn.lock
Labels: merge, ready for review

#170 [Events] Re-integrate Schedule data, refine Layout and Chat design
  src/content-single/EventContentItem/EventDetail.sandbox.js
  src/content-single/EventContentItem/components/CallsToAction.js
  src/content-single/EventContentItem/components/CampusSelector.js
  src/content-single/EventContentItem/components/DirectMessagesChat.js
  src/content-single/EventContentItem/components/EventChat.js
  src/content-single/EventContentItem/components/EventChatOffline.js
  src/content-single/EventContentItem/components/EventDescriptionCard.js
  src/content-single/EventContentItem/components/EventMedia.js
  src/content-single/EventContentItem/components/EventPanel.js
  src/content-single/EventContentItem/components/EventSchedule.js
  src/content-single/EventContentItem/components/EventScheduleConnected.js
  src/content-single/EventContentItem/components/EventScheduleTimes.js
  src/content-single/EventContentItem/components/LiveStreamChat.js
  src/content-single/EventContentItem/index.sandbox.js
  src/fragmentTypes.json
  src/styles/css/stream-chat-react.overrides.css
  src/styles/theme.js
  src/ui/chat/MessageInput.js
Labels: merge

#171 [Chat] Chat Channel ID and Event Metadata
  src/content-single/EventContentItem/components/EventChat.js
  src/content-single/EventContentItem/components/EventPanel.js
  src/content-single/EventContentItem/index.sandbox.js
  src/live/getLiveContent.js
Labels: ready for review

#172 [Events] Message Actions & Moderation
  package.json
  src/content-single/EventContentItem/components/EventChat.js
  src/content-single/EventContentItem/components/EventSchedule.js
  src/content-single/EventContentItem/components/LiveStreamChat.js
  src/fragmentTypes.json
  src/stream-chat-client/chatRoles.js
  src/stream-chat-client/chatUtils.js
  src/stream-chat-client/index.js
  src/styles/css/stream-chat-react.overrides.css
  src/styles/theme.js
  src/ui/Icons/Icon.js
  src/ui/Icons/index.js
  src/ui/Icons/paper-airplane.js
  src/ui/Icons/three-dots.js
  src/ui/chat/Message.js
  src/ui/chat/MessageActionsDropdown.js
  src/ui/chat/MessageInput.js
  src/ui/chat/getMessageActionOptions.js
  yarn.lock
Labels: ready for review
